version: '3.9'

x-volumes: &app-volumes
  - ./:/app:cached
  - ~/.ssh:/root/.ssh
  - ~/.bash_history:/root/.bash_history
  - ~/.bashrc:/root/.bashrc:delegated
  - /var/run/docker.sock:/var/run/docker.sock

services:
  app:
    build: .
    volumes: *app-volumes
    env_file:
        - .env
    ports:
      - 4000:4000
    depends_on:
      - video_dating_db
    command: yarn dev
    tty: true
    stdin_open: true

  video_dating_db:
    image: postgres:14.2
    container_name: video_dating_db
    restart: unless-stopped
    env_file:
        - .env
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  video_dating_pgadmin:
    image: dpage/pgadmin4:6.8
    container_name: video_dating_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - 5050:80
    restart: unless-stopped
    depends_on:
      - video_dating_db


volumes:
  pgdata:
  pgadmin:
